[package]
name = "audio-visualization"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
cpal = "0.15.3"
itertools = "0.13.0"
ringbuf = "0.4.7"
tokio = { version = "1.42.0", features = ["full"] }
